In [1]:
import os, copy, sys
import numpy as np
import pandas as pd
from typing import List, Tuple

In [2]:
# Run this cell to remove pool_alice_code from package namespace, and reimport it with most recent changes
sys.modules.pop("pool_alice_code",None)
import pool_alice_code

# Load data and explore a little (note: most of the exploration is in the "automation_final_project/data" under the respective datasets)

In [3]:
os.getcwd()

'/home/ethan/02750-automation/automation_final_project/P_ALICE'

In [4]:
X: np.ndarray = np.load('../data/logd74/fingerprints.npy')
y: np.ndarray  = np.load('../data/logd74/logd74s.npy')

X_df = pd.DataFrame(X)
print(X_df.shape)
X_df.head()

(1130, 2048)

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
X_df.describe()

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
count,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,...,1130.000000,1130.0,1130.0,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000
mean,0.000885,0.238053,0.069027,0.011504,0.022124,0.026549,0.002655,0.007965,0.007965,0.030973,...,0.024779,0.0,0.0,0.021239,0.010619,0.006195,0.007965,0.019469,0.011504,0.011504
std,0.029748,0.426080,0.253612,0.106687,0.147152,0.160831,0.051480,0.088928,0.088928,0.173322,...,0.155519,0.0,0.0,0.144244,0.102548,0.078497,0.088928,0.138228,0.106687,0.106687
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
# https://stackoverflow.com/questions/17071871/how-do-i-select-rows-from-a-dataframe-based-on-column-values
description = X_df.describe().transpose()

zero_std = description.loc[description['std'] == 0]

zero_std

       count  mean  std  min  25%  50%  75%  max
10    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
19    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
22    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
44    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
55    1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...   ...  ...  ...  ...  ...  ...  ...
1987  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
1996  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2015  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2039  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
2040  1130.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

[95 rows x 8 columns]

In [7]:
bad_features = zero_std.transpose().columns
zero_std.transpose().columns

Index([  10,   19,   22,   44,   55,   86,  101,  127,  148,  152,  161,  167,
        178,  181,  188,  228,  229,  256,  267,  285,  324,  332,  356,  388,
        393,  417,  439,  445,  468,  492,  505,  509,  532,  572,  605,  608,
        619,  659,  662,  685,  733,  740,  818,  866,  877,  920,  923,  934,
        938,  945,  956,  986,  988,  995, 1072, 1098, 1111, 1115, 1122, 1177,
       1186, 1247, 1259, 1315, 1345, 1406, 1500, 1529, 1545, 1558, 1562, 1595,
       1628, 1641, 1644, 1686, 1703, 1709, 1720, 1740, 1784, 1787, 1793, 1834,
       1846, 1869, 1874, 1881, 1931, 1955, 1987, 1996, 2015, 2039, 2040],
      dtype='int64')

In [8]:
X_df = X_df.drop(labels=bad_features,axis=1)
print(X_df.shape)
X_df.head()

(1130, 1953)

,0,1,2,3,4,5,6,7,8,9,...,2036,2037,2038,2041,2042,2043,2044,2045,2046,2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X = X_df.to_numpy()
num_original_features = len(X[0])

# constants

In [10]:
SEEDS = [i*1001 for i in range(1,6)]

SEEDS

[1001, 2002, 3003, 4004, 5005]

In [11]:
BATCH_SIZE = 16

# P-ALICE, weighted linear regression

In [12]:
X_pool_linear = np.vstack((X.T,np.ones(len(X)))).T
X_pool_linear

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [13]:
num_features_linear = len(X_pool_linear[0])
basis_funcs_linear: List[np.ufunc] = [pool_alice_code.identity_basis for _ in range(num_features_linear)] # type: ignore

sim_args = {'n':len(SEEDS),
            'seeds':SEEDS,
            'X_pool':X_pool_linear,
            'y_pool':y,
            'basis_funcs':basis_funcs_linear,
            'passive_learning':False,
            'batch_size':BATCH_SIZE}
logd74_linear_palice_16, logd74_linear_palice_16_cor = pool_alice_code.generate_or_load_result(\
    result_file_name='logd74_linear_palice_16',
    sim_args=sim_args,
    overwrite_results=False)

generating results...

______________________________________________
simulation number=1, prng_seed=1001,start_time=1714163026.282627
percentage complete: 20.0,	time elapsed since start=0.0001938343048095703 seconds

percentage complete: 25.0,	time elapsed since start=333.7781217098236 seconds
percentage complete: 45.0,	time elapsed since start=1636.7612028121948 seconds
percentage complete: 50.0,	time elapsed since start=1991.7510304450989 seconds
Elapsed Time: 2111.6271057128906 seconds

______________________________________________
simulation number=2, prng_seed=2002,start_time=1714165137.9234426
percentage complete: 20.0,	time elapsed since start=0.0001690387725830078 seconds
percentage complete: 25.0,	time elapsed since start=335.58907103538513 seconds
percentage complete: 45.0,	time elapsed since start=1623.5288364887238 seconds
percentage complete: 50.0,	time elapsed since start=1984.797471523285 seconds
Elapsed Time: 2106.723709821701 seconds

______________________________________________
simulation number=3, prng_seed=3003,start_time=1714167244.6594203
percentage complete: 20.0,	time elapsed since start=0.00013065338134765625 seconds
percentage complete: 25.0,	time elapsed since start=336.54437351226807 seconds
percentage complete: 45.0,	time elapsed since start=1608.685387134552 seconds
percentage complete: 50.0,	time elapsed since start=1968.0176000595093 seconds
Elapsed Time: 2089.7973489761353 seconds

______________________________________________
simulation number=4, prng_seed=4004,start_time=1714169334.4699173
percentage complete: 20.0,	time elapsed since start=0.00021386146545410156 seconds
percentage complete: 25.0,	time elapsed since start=338.3658814430237 seconds
percentage complete: 45.0,	time elapsed since start=1622.758662700653 seconds
percentage complete: 50.0,	time elapsed since start=1983.2940020561218 seconds
Elapsed Time: 2104.2048342227936 seconds

______________________________________________
simulation number=5, prng_seed=5005,start_time=1714171438.687695
percentage complete: 20.0,	time elapsed since start=0.00015234947204589844 seconds
percentage complete: 25.0,	time elapsed since start=341.66525530815125 seconds
percentage complete: 45.0,	time elapsed since start=1627.2443652153015 seconds
percentage complete: 50.0,	time elapsed since start=1989.492623090744 seconds
Elapsed Time: 2111.202116727829 seconds
TOTAL Elapsed Time: 10523.632146835327 seconds (175.3938691139221 min)

In [14]:
# check the results are consistent with expectation

x_train_length = len(X)*0.8
twenty_percent = int(x_train_length * 0.20)
fifty_percent = int(x_train_length * 0.5)
num_samples_axis = range(twenty_percent,fifty_percent+1,BATCH_SIZE)
print(num_samples_axis)
print(len(num_samples_axis))

range(180, 453, 16)
18

In [15]:
assert logd74_linear_palice_16.shape[1] == len(num_samples_axis), "The number of iterations is off"

logd74_linear_palice_16.shape

(5, 18)

# passive (random) learning, linear regression

In [16]:
# try:
#     logd74_linear_random_16: np.ndarray = np.load('../results/logd74_linear_random_16.npy')
#     print("RESULTS ALREADY OBTAINED\nNOTE: TOTAL Elapsed Time: 1129.4733316898346 seconds (18.82455552816391 min)")
# except:
#     logd74_linear_random_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_linear,y_pool=y,basis_funcs=basis_funcs_linear,passive_learning=True,batch_size=BATCH_SIZE)
    
#     np.save('../results/logd74_linear_random_16.npy', logd74_linear_random_16)

sim_args = {'n':len(SEEDS),
            'seeds':SEEDS,
            'X_pool':X_pool_linear,
            'y_pool':y,
            'basis_funcs':basis_funcs_linear,
            'passive_learning':True,
            'batch_size':BATCH_SIZE}
logd74_linear_random_16, logd74_linear_random_16_cor = pool_alice_code.generate_or_load_result(\
    result_file_name='logd74_linear_random_16',
    sim_args=sim_args,
    overwrite_results=False)

generating results...

______________________________________________
simulation number=1, prng_seed=1001,start_time=1714173550.1613374
percentage complete: 20.0,	time elapsed since start=0.00023674964904785156 seconds

percentage complete: 25.0,	time elapsed since start=24.60729479789734 seconds
percentage complete: 45.0,	time elapsed since start=114.47006440162659 seconds
percentage complete: 50.0,	time elapsed since start=139.2056062221527 seconds
Elapsed Time: 147.3260042667389 seconds

______________________________________________
simulation number=2, prng_seed=2002,start_time=1714173697.5006487
percentage complete: 20.0,	time elapsed since start=0.00014662742614746094 seconds
percentage complete: 25.0,	time elapsed since start=23.79667901992798 seconds
percentage complete: 45.0,	time elapsed since start=114.23513460159302 seconds
percentage complete: 50.0,	time elapsed since start=139.23892307281494 seconds
Elapsed Time: 147.6365818977356 seconds

______________________________________________
simulation number=3, prng_seed=3003,start_time=1714173845.1489131
percentage complete: 20.0,	time elapsed since start=0.00013828277587890625 seconds
percentage complete: 25.0,	time elapsed since start=24.237664222717285 seconds
percentage complete: 45.0,	time elapsed since start=114.04290795326233 seconds
percentage complete: 50.0,	time elapsed since start=138.89786648750305 seconds
Elapsed Time: 147.39018559455872 seconds

______________________________________________
simulation number=4, prng_seed=4004,start_time=1714173992.5506077
percentage complete: 20.0,	time elapsed since start=0.00012993812561035156 seconds
percentage complete: 25.0,	time elapsed since start=24.044679641723633 seconds
percentage complete: 45.0,	time elapsed since start=113.12045645713806 seconds
percentage complete: 50.0,	time elapsed since start=137.50792598724365 seconds
Elapsed Time: 145.93234729766846 seconds

______________________________________________
simulation number=5, prng_seed=5005,start_time=1714174138.4951017
percentage complete: 20.0,	time elapsed since start=0.00018024444580078125 seconds
percentage complete: 25.0,	time elapsed since start=24.111023426055908 seconds
percentage complete: 45.0,	time elapsed since start=114.3777506351471 seconds
percentage complete: 50.0,	time elapsed since start=139.29732060432434 seconds
Elapsed Time: 147.57274961471558 seconds
TOTAL Elapsed Time: 735.9217758178711 seconds (12.26536293029785 min)

# P-ALICE, nonlinear regression 1

## define basis functions for nonlinear regression 1

In [17]:
dummy = np.array([1,0,1,0])
print(dummy)

pool_alice_code.map_to_off_on_basis(dummy) # now, not having a certain motif can be penalized

[1 0 1 0]

array([ 1, -1,  1, -1])

In [18]:
X_pool_nonlinear_1 = np.vstack((X.T,np.ones(len(X)))).T
X_pool_nonlinear_1

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
basis_funcs_nonlinear_1: List[np.ufunc] = [pool_alice_code.map_to_off_on_basis for i in range(0,len(X_pool_nonlinear_1[0]))] # type: ignore
basis_funcs_nonlinear_1[-1] = pool_alice_code.identity_basis # type: ignore

assert len(X_pool_nonlinear_1[0]) == len(basis_funcs_nonlinear_1), f"len(X_pool_nonlinear_1[0]) == len(basis_funcs_nonlinear_1) is not true for {len(X_pool_nonlinear_1[0])} == {len(basis_funcs_nonlinear_1)}"

## perform PALICE for nonlinear regression 1

In [20]:
# try:
#     logd74_nonlinear_palice_16: np.ndarray = np.load('../results/logd74_nonlinear_palice_16.npy')
#     print("RESULTS ALREADY OBTAINED\n Note, TOTAL Elapsed Time: 11185.348386764526 seconds (186.4224731127421 min)")
# except:
#     logd74_nonlinear_palice_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_nonlinear_1,y_pool=y,basis_funcs=basis_funcs_nonlinear_1,batch_size=BATCH_SIZE,passive_learning=False)
#     np.save('../results/logd74_nonlinear_palice_16.npy', logd74_nonlinear_palice_16)

sim_args = {'n':len(SEEDS),
            'seeds':SEEDS,
            'X_pool':X_pool_nonlinear_1,
            'y_pool':y,
            'basis_funcs':basis_funcs_nonlinear_1,
            'passive_learning':False,
            'batch_size':BATCH_SIZE}
logd74_nonlinear_palice_16, logd74_nonlinear_palice_16_cor = pool_alice_code.generate_or_load_result(\
    result_file_name='logd74_nonlinear_palice_16',
    sim_args=sim_args,
    overwrite_results=False)

generating results...

______________________________________________
simulation number=1, prng_seed=1001,start_time=1714174286.2396176
percentage complete: 20.0,	time elapsed since start=0.00021338462829589844 seconds

percentage complete: 25.0,	time elapsed since start=337.35276532173157 seconds
percentage complete: 45.0,	time elapsed since start=1611.9711227416992 seconds
percentage complete: 50.0,	time elapsed since start=1970.9057002067566 seconds
Elapsed Time: 2091.293606042862 seconds

______________________________________________
simulation number=2, prng_seed=2002,start_time=1714176377.5664456
percentage complete: 20.0,	time elapsed since start=0.00014901161193847656 seconds
percentage complete: 25.0,	time elapsed since start=336.79030084609985 seconds
percentage complete: 45.0,	time elapsed since start=1614.1446039676666 seconds
percentage complete: 50.0,	time elapsed since start=1972.4540717601776 seconds
Elapsed Time: 2092.6217272281647 seconds

______________________________________________
simulation number=3, prng_seed=3003,start_time=1714178470.219534
percentage complete: 20.0,	time elapsed since start=0.0002295970916748047 seconds
percentage complete: 25.0,	time elapsed since start=336.6085727214813 seconds
percentage complete: 45.0,	time elapsed since start=1611.1845405101776 seconds
percentage complete: 50.0,	time elapsed since start=1969.475545167923 seconds
Elapsed Time: 2088.2916507720947 seconds

______________________________________________
simulation number=4, prng_seed=4004,start_time=1714180558.5445218
percentage complete: 20.0,	time elapsed since start=0.0001399517059326172 seconds
percentage complete: 25.0,	time elapsed since start=336.781955242157 seconds
percentage complete: 45.0,	time elapsed since start=1611.6180934906006 seconds
percentage complete: 50.0,	time elapsed since start=1970.9437327384949 seconds
Elapsed Time: 2091.1549429893494 seconds

______________________________________________
simulation number=5, prng_seed=5005,start_time=1714182649.7319067
percentage complete: 20.0,	time elapsed since start=0.00015783309936523438 seconds
percentage complete: 25.0,	time elapsed since start=338.11494159698486 seconds
percentage complete: 45.0,	time elapsed since start=1610.8139925003052 seconds
percentage complete: 50.0,	time elapsed since start=1969.0342936515808 seconds
Elapsed Time: 2090.1211247444153 seconds
TOTAL Elapsed Time: 10453.650905370712 seconds (174.22751508951188 min)

# random (passive), nonlinear regression 1

In [21]:
# try:
#     logd74_nonlinear_random_16: np.ndarray = np.load('../results/logd74_nonlinear_random_16.npy')
#     print("RESULTS ALREADY OBTAINED\nNOTE: TOTAL Elapsed Time: 812.0736465454102 seconds (13.534560775756836 min)")
# except:
#     logd74_nonlinear_random_16 = pool_alice_code.simulate_pool_alice_n_times(n=len(SEEDS),seeds=SEEDS,X_pool=X_pool_nonlinear_1,y_pool=y,basis_funcs=basis_funcs_nonlinear_1,passive_learning=True,batch_size=BATCH_SIZE)
    
#     np.save('../results/logd74_nonlinear_random_16.npy', logd74_nonlinear_random_16)

sim_args = {'n':len(SEEDS),
            'seeds':SEEDS,
            'X_pool':X_pool_nonlinear_1,
            'y_pool':y,
            'basis_funcs':basis_funcs_nonlinear_1,
            'passive_learning':True,
            'batch_size':BATCH_SIZE}
logd74_nonlinear_random_16, logd74_nonlinear_random_16_cor = pool_alice_code.generate_or_load_result(\
    result_file_name='logd74_nonlinear_random_16',
    sim_args=sim_args,
    overwrite_results=False)

generating results...

______________________________________________
simulation number=1, prng_seed=1001,start_time=1714184739.929983
percentage complete: 20.0,	time elapsed since start=0.00015091896057128906 seconds
percentage complete: 25.0,	time elapsed since start=24.58765482902527 seconds
percentage complete: 45.0,	time elapsed since start=114.35463857650757 seconds
percentage complete: 50.0,	time elapsed since start=138.77844524383545 seconds
Elapsed Time: 147.2161204814911 seconds

______________________________________________
simulation number=2, prng_seed=2002,start_time=1714184887.180393
percentage complete: 20.0,	time elapsed since start=0.00014519691467285156 seconds
percentage complete: 25.0,	time elapsed since start=24.091770887374878 seconds
percentage complete: 45.0,	time elapsed since start=113.99296259880066 seconds
percentage complete: 50.0,	time elapsed since start=138.7756941318512 seconds
Elapsed Time: 146.89689445495605 seconds

______________________________________________
simulation number=3, prng_seed=3003,start_time=1714185034.1142497
percentage complete: 20.0,	time elapsed since start=0.0002052783966064453 seconds
percentage complete: 25.0,	time elapsed since start=23.93087363243103 seconds
percentage complete: 45.0,	time elapsed since start=113.12087726593018 seconds
percentage complete: 50.0,	time elapsed since start=137.5982460975647 seconds
Elapsed Time: 146.11401200294495 seconds

______________________________________________
simulation number=4, prng_seed=4004,start_time=1714185180.2631254
percentage complete: 20.0,	time elapsed since start=0.00017333030700683594 seconds
percentage complete: 25.0,	time elapsed since start=24.165717840194702 seconds
percentage complete: 45.0,	time elapsed since start=113.74541687965393 seconds
percentage complete: 50.0,	time elapsed since start=138.50443196296692 seconds
Elapsed Time: 146.9187445640564 seconds

______________________________________________
simulation number=5, prng_seed=5005,start_time=1714185327.2114418
percentage complete: 20.0,	time elapsed since start=0.00013303756713867188 seconds
percentage complete: 25.0,	time elapsed since start=24.062381505966187 seconds
percentage complete: 45.0,	time elapsed since start=114.26615118980408 seconds
percentage complete: 50.0,	time elapsed since start=139.17867636680603 seconds
Elapsed Time: 147.341402053833 seconds
TOTAL Elapsed Time: 734.658483505249 seconds (12.244308058420817 min)

# Get the batch_size 32 results

In [22]:
print(len(num_samples_axis))
print(len(list(num_samples_axis[::2])))
logd74_nonlinear_random_16.shape

18
9

(5, 18)

In [23]:
logd74_nonlinear_random_16[:,::2].shape

(5, 9)

In [24]:
try:
    np.load('../results/logd74_linear_random_32.npy')
    np.load('../results/logd74_linear_random_32_cor.npy')
    print('results already obtained')
except:
    print('generating results')
    np.save('../results/logd74_linear_palice_32.npy',logd74_linear_palice_16[:,::2])
    np.save('../results/logd74_linear_random_32.npy',logd74_linear_random_16[:,::2])
    np.save('../results/logd74_nonlinear_palice_32.npy',logd74_nonlinear_palice_16[:,::2])
    np.save('../results/logd74_nonlinear_random_32.npy',logd74_nonlinear_random_16[:,::2])

    np.save('../results/logd74_linear_palice_32_cor.npy',logd74_linear_palice_16_cor[:,::2])
    np.save('../results/logd74_linear_random_32_cor.npy',logd74_linear_random_16_cor[:,::2])
    np.save('../results/logd74_nonlinear_palice_32_cor.npy',logd74_nonlinear_palice_16_cor[:,::2])
    np.save('../results/logd74_nonlinear_random_32_cor.npy',logd74_nonlinear_random_16_cor[:,::2])

generating results